#!/usr/bin/env python3
# extract_acphy_tables_from_descriptor.py
#
# Walks the static descriptor arrays acphytbl_info_rev{0,2} found in .rodata
# of the wl driver, decodes each entry, follows the relocation on entry.ptr to
# resolve which static table it points to, and dumps every table as a C array.
#
# This is the right entry point for AC-PHY init tables: the canonical Broadcom
# pattern is one descriptor array per PHY revision, walked in a loop by
# wlc_phy_init_acphy or wlc_phy_tbl_init_acphy.

import sys, os, re, struct
from collections import namedtuple
from elftools.elf.elffile import ELFFile

DESCRIPTOR_SIZE = 20  # u32 ptr + u32 len + u32 id + u32 off + u32 width
DESCRIPTOR_FIELDS = ['ptr', 'len', 'id', 'off', 'width']

Entry = namedtuple('Entry', ['descriptor_idx',
                             'ptr_sym', 'ptr_addend',
                             'length', 'id_', 'off', 'width'])

def main():
    if len(sys.argv) < 3:
        print(f"usage: {sys.argv[0]} <wl.o> <output_dir>", file=sys.stderr)
        sys.exit(1)
    elf_path = sys.argv[1]
    outdir = sys.argv[2]
    os.makedirs(outdir, exist_ok=True)

    with open(elf_path, 'rb') as f:
        elf = ELFFile(f)

        # Build symbol table: name -> (section_index, value, size).
        sym_by_name = {}
        sym_by_addr = {}  # (section_index, value) -> name (used to resolve relocs)
        symtab = elf.get_section_by_name('.symtab')
        for sym in symtab.iter_symbols():
            shndx = sym.entry['st_shndx']
            if not isinstance(shndx, int) or shndx == 0:
                continue
            name = sym.name
            if not name:
                continue
            sym_by_name[name] = (shndx, sym.entry['st_value'], sym.entry['st_size'])
            sym_by_addr[(shndx, sym.entry['st_value'])] = name

        # Map section index -> (name, bytes).
        sect_data = {}
        sect_name_to_idx = {}
        for idx, s in enumerate(elf.iter_sections()):
            sect_data[idx] = (s.name, s.data() if s.header['sh_flags'] & 0x2 else b'')
            sect_name_to_idx[s.name] = idx

        # Build a per-section relocation index:
        #   reloc_at[(target_section_index, offset)] = (sym_name, sym_addend_in_sym)
        # In MIPS REL the addend is in the section bytes itself, so we read
        # both the integer at that offset and the relocation target.
        reloc_at = {}
        for s in elf.iter_sections():
            if s.header['sh_type'] != 'SHT_REL':
                continue
            target_idx = s.header['sh_info']
            link_symtab = elf.get_section(s.header['sh_link'])
            for r in s.iter_relocations():
                rsym = link_symtab.get_symbol(r.entry['r_info_sym'])
                rtype = r.entry['r_info_type']
                # MIPS R_MIPS_32 = type 2: full 32-bit absolute (used in .data/.rodata).
                # Other MIPS reloc types in code are HI16/LO16/26.
                # For descriptor arrays we expect R_MIPS_32 on the ptr field.
                reloc_at.setdefault((target_idx, r.entry['r_offset']), []).append(
                    (rtype, rsym.name, rsym.entry['st_value']))

        # Open output.
        out_c = open(os.path.join(outdir, 'acphy_tables_full.c'), 'w')
        out_idx = open(os.path.join(outdir, 'acphy_tables_index.txt'), 'w')
        out_c.write("/* Autogenerated. Walks acphytbl_info_rev{0,2} descriptor\n"
                    " * arrays and dumps every static table they point to.\n"
                    " * Source: " + os.path.basename(elf_path) + "\n */\n\n")

        seen_tables = {}  # sym_name -> True

        for desc_name in ('acphytbl_info_rev0', 'acphytbl_info_rev2'):
            if desc_name not in sym_by_name:
                print(f"# {desc_name} not in symbol table, skipping", file=sys.stderr)
                continue
            shndx, value, size = sym_by_name[desc_name]
            sect_name, data = sect_data[shndx]
            n_entries = size // DESCRIPTOR_SIZE

            print(f"# {desc_name} in {sect_name} @ {value:#x}, {size} bytes "
                  f"= {n_entries} descriptor entries")
            out_c.write(f"\n/* ===== {desc_name}: {n_entries} entries ===== */\n\n")
            out_idx.write(f"=== {desc_name} ({n_entries} entries) ===\n")

            for i in range(n_entries):
                base = value + i * DESCRIPTOR_SIZE

                # Read all 5 u32 fields (big-endian).
                fields = struct.unpack('>5I', data[base:base + DESCRIPTOR_SIZE])
                ptr_addend, length, id_, off, width = fields

                # Resolve ptr field via R_MIPS_32 reloc on (shndx, base+0).
                relocs_here = reloc_at.get((shndx, base + 0), [])
                ptr_sym = None
                for rtype, rname, rval in relocs_here:
                    # rtype 2 == R_MIPS_32; we accept anything for the ptr slot.
                    ptr_sym = rname
                    break

                line = (f"  [{i:2d}] id={id_:#5x} len={length:#6x} off={off:#6x} "
                        f"width={width:>2} ptr={ptr_sym or '???'}")
                if ptr_addend:
                    line += f"+{ptr_addend:#x}"
                out_idx.write(line + "\n")

                if ptr_sym is None:
                    out_c.write(f"/* entry [{i}]: id={id_:#x} len={length:#x} "
                                f"off={off:#x} width={width} — unresolved ptr */\n\n")
                    continue

                # Resolve target bytes.
                if ptr_sym not in sym_by_name:
                    out_c.write(f"/* entry [{i}]: target {ptr_sym} not in symtab */\n\n")
                    continue
                tshndx, tvalue, tsize = sym_by_name[ptr_sym]
                tsect_name, tdata = sect_data[tshndx]

                nbytes = length * (width // 8) if width >= 8 else length * 2
                start = tvalue + ptr_addend
                end = start + nbytes
                if end > len(tdata):
                    out_c.write(f"/* entry [{i}]: out of bounds for {ptr_sym} "
                                f"(want {nbytes} bytes, sym size {tsize}) */\n\n")
                    continue

                payload = tdata[start:end]

                # Format payload.
                if width == 32:
                    ctype, step = 'u32', 4
                    per_line = 6
                    fmt_w = 8
                elif width == 16:
                    ctype, step = 'u16', 2
                    per_line = 12
                    fmt_w = 4
                elif width == 8:
                    ctype, step = 'u8', 1
                    per_line = 16
                    fmt_w = 2
                elif width == 48:
                    # Treat as triplets of u16: format with 3 per logical entry.
                    ctype, step = 'u16', 2
                    per_line = 12
                    fmt_w = 4
                else:
                    ctype, step = 'u8', 1
                    per_line = 16
                    fmt_w = 2

                words = []
                for k in range(0, len(payload), step):
                    chunk = payload[k:k+step]
                    if len(chunk) < step:
                        break
                    words.append(int.from_bytes(chunk, 'big'))

                count_decl = length if width in (8, 16, 32) \
                             else (length * width // 16)  # express as u16 array length

                hint = (f"descriptor[{i}] of {desc_name}: "
                        f"id={id_:#x}, len={length}, off={off:#x}, width={width}")
                out_c.write(f"/* {hint} */\n")
                out_c.write(f"static const {ctype} {ptr_sym}[{count_decl}] = {{\n")
                for k in range(0, len(words), per_line):
                    line = ', '.join(f"0x{w:0{fmt_w}x}" for w in words[k:k+per_line])
                    out_c.write(f"\t{line},\n")
                out_c.write("};\n\n")

                seen_tables[ptr_sym] = True

            out_idx.write("\n")

        out_c.close()
        out_idx.close()

        print(f"# Tables dumped: {len(seen_tables)}")
        print(f"# Files: {outdir}/acphy_tables_full.c, {outdir}/acphy_tables_index.txt")

if __name__ == '__main__':
    main()
