#!/usr/bin/env python3
# extract_acphy_txgain.py
#
# Dumps the orphan acphy_txgain_* tables that descriptor-driven extraction
# (extract_acphy_tables_from_descriptor.py) does not cover, because they are
# not in acphytbl_info_rev{0,2}.
#
# Call-site shape recovered by reading wlc_phy_set_regtbl_on_band_change_acphy:
# every reference converges on a single wlc_phy_table_write_acphy call at
# 0x41e94 with (id=0x20, len=128, off=0, width=48). 768 bytes / entry of
# 6 bytes => 128 entries, matching the .data symbol size for all variants.
#
# width=48 is laid out as 3 u16 per logical entry (same convention used by
# extract_acphy_tables_from_descriptor.py for width 48).
#
# Note on acphy_txgain_epa_5g_2069rev254: the symbol is global STT_OBJECT
# with size 768 but has zero relocations inside wl.o. Same family naming
# and matching size strongly suggest the same shape; we dump it on that
# basis but the (id, off) tuple is not directly verifiable from this binary.

import os, sys, struct, hashlib
from elftools.elf.elffile import ELFFile

ID, LEN, OFF, WIDTH = 0x20, 128, 0, 48           # from call site 0x41e94
BYTES_PER_ENTRY = WIDTH // 8                     # 6
EXPECTED_SIZE = LEN * BYTES_PER_ENTRY            # 768

PROVEN_FROM_RELOCS = {
    'acphy_txgain_epa_2g_2069rev0',  'acphy_txgain_epa_2g_2069rev4',
    'acphy_txgain_epa_2g_2069rev16', 'acphy_txgain_epa_2g_2069rev17',
    'acphy_txgain_epa_2g_2069rev18',
    'acphy_txgain_epa_5g_2069rev0',  'acphy_txgain_epa_5g_2069rev4',
    'acphy_txgain_epa_5g_2069rev16', 'acphy_txgain_epa_5g_2069rev17',
    'acphy_txgain_epa_5g_2069rev18',
    'acphy_txgain_ipa_2g_2069rev0',
    'acphy_txgain_ipa_2g_2069rev16', 'acphy_txgain_ipa_2g_2069rev17',
    'acphy_txgain_ipa_2g_2069rev18',
    'acphy_txgain_ipa_5g_2069rev0',
    'acphy_txgain_ipa_5g_2069rev16', 'acphy_txgain_ipa_5g_2069rev17',
    'acphy_txgain_ipa_5g_2069rev18',
}
UNREFERENCED = {'acphy_txgain_epa_5g_2069rev254'}


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <wl.o> <output_dir>", file=sys.stderr)
        sys.exit(1)
    elf_path, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)

    with open(elf_path, 'rb') as f:
        sha = hashlib.sha256(f.read()).hexdigest()
    src = os.path.basename(elf_path)

    syms = sorted(PROVEN_FROM_RELOCS | UNREFERENCED)

    out_c = open(os.path.join(outdir, 'acphy_txgain_tables.c'), 'w')
    out_idx = open(os.path.join(outdir, 'acphy_txgain_index.txt'), 'w')

    out_c.write(
        f"/* Autogenerated by extract_acphy_txgain.py.\n"
        f" * Source: {src} (sha256:{sha}).\n"
        f" * Call-site shape (id=0x{ID:x}, len={LEN}, off={OFF}, width={WIDTH})\n"
        f" *   recovered at 0x41e94 in wlc_phy_set_regtbl_on_band_change_acphy.\n"
        f" * 18 of 19 symbols are reached through that single jalr; one\n"
        f" * (acphy_txgain_epa_5g_2069rev254) is unreferenced inside wl.o\n"
        f" *   and is dumped on size+naming evidence only.\n"
        f" */\n\n"
    )
    out_idx.write(f"# acphy_txgain_* dump from {src}\n")
    out_idx.write(f"# id=0x{ID:x} len={LEN} off=0x{OFF:x} width={WIDTH}\n")
    out_idx.write(f"# {'symbol':<40}  {'bytes':>5}  evidence\n")

    with open(elf_path, 'rb') as f:
        elf = ELFFile(f)
        symtab = elf.get_section_by_name('.symtab')
        sym_by_name = {s.name: s for s in symtab.iter_symbols()}
        sect_data = {i: s.data() for i, s in enumerate(elf.iter_sections())
                     if s.header['sh_flags'] & 0x2}

        for name in syms:
            if name not in sym_by_name:
                out_idx.write(f"  {name:<40}  MISSING from .symtab\n")
                continue
            s = sym_by_name[name]
            shndx, val, sz = s['st_shndx'], s['st_value'], s['st_size']
            evidence = "reloc-proven" if name in PROVEN_FROM_RELOCS else "size-only"
            out_idx.write(f"  {name:<40}  {sz:>5}  {evidence}\n")

            if sz != EXPECTED_SIZE:
                out_c.write(f"/* {name}: size {sz} != expected {EXPECTED_SIZE},"
                            f" skipped */\n\n")
                continue
            if shndx not in sect_data:
                out_c.write(f"/* {name}: section {shndx} has no data */\n\n")
                continue

            payload = sect_data[shndx][val:val + sz]
            words = struct.unpack(f'>{LEN * 3}H', payload)  # 3 u16 per entry

            out_c.write(f"/* {name}: {evidence}; "
                        f"{LEN} entries x 3 u16 (width=48) */\n")
            out_c.write(f"static const u16 {name}[{LEN * 3}] = {{\n")
            for i in range(LEN):
                a, b, c = words[i*3:i*3+3]
                out_c.write(f"\t0x{a:04x}, 0x{b:04x}, 0x{c:04x},  "
                            f"/* [{i:3d}] */\n")
            out_c.write("};\n\n")

    out_c.close()
    out_idx.close()
    print(f"# wrote {outdir}/acphy_txgain_tables.c, "
          f"{outdir}/acphy_txgain_index.txt")


if __name__ == '__main__':
    main()
