/*
 * extract_r11.c — body of bcma_sprom_extract_r11() and its helper
 * bcma_sprom_unpack_rxgains(), derived from
 * 0001-ssb-bcma-firmware-SROM-revision-11-support.patch
 * (drivers/bcma/sprom.c hunk).
 *
 * Three modifications relative to the patch as currently written,
 * all in the header-extraction block, all of the same kind:
 *
 *     SSB_SPROM8_IL0MAC    -> SSB_SPROM11_IL0MAC    (0x008C -> 0x0090)
 *     SSB_SPROM8_ANTAVAIL  -> SSB_SPROM11_ANTAVAIL  (0x009C -> 0x00A0)
 *     SSB_SPROM8_TXRXC     -> SSB_SPROM11_TXRXC     (0x00A2 -> 0x00A8)
 *
 * Only the byte offset is changed; the bitfield masks/shifts stay
 * the SSB_SPROM8_* values because the field layout within each word
 * is unchanged between rev 8 and rev 11.
 *
 * Rationale: the patch as posted reuses the SSB_SPROM8_* offsets
 * for these three header symbols, asserting in its commit message
 * that "Header fields ... share their byte offsets with rev 8 on
 * the reference board". This harness's diff against `wl nvram_dump`
 * for the DSL-3580L falsifies that assertion: the values nvram
 * reports for aa{2,5}g, txchain, rxchain, antswitch, and macaddr
 * appear in the SROM dump at offsets +4 / +6 / +4 byte (resp.) past
 * the rev-8 positions. Boardrev (0x82) does coincide and is left
 * alone. The new SSB_SPROM11_* offsets defined in ssb_regs.h are
 * the value-matched positions on the reference board.
 *
 * If a second rev-11 board contradicts these positions, the patch
 * will need a more elaborate fix (per-board layout? subband5gver
 * branching?). Until then, this is the working extraction.
 *
 * DO NOT EDIT THIS FILE TO MAKE THE TEST PASS. The whole point of
 * the harness is that this file mirrors the parser going to
 * mainline. If the test fails on a new vector, the discussion
 * belongs in the patch, not here.
 */

#include "kernel_shim.h"
#include "ssb_sprom.h"
#include "ssb_regs.h"

/* === BEGIN PARSER BODY (header symbols re-routed to SPROM11_*) ========== */

static void bcma_sprom_unpack_rxgains(struct ssb_sprom_rxgains *out,
				      int chain, u8 packed)
{
	/* Per-byte rxgains encoding (verified on DSL-3580L, all chains):
	 * bit 7    = trelnabyp (T/R-eLNA bypass select)
	 * bits 6:3 = triso     (T/R isolation, 4-bit code)
	 * bits 2:0 = elnagain  (eLNA gain stage select, 3-bit code)
	 *
	 * Each chain carries its own rxgains pack in its per-chain power
	 * info block; the same encoding applies across chains. The
	 * struct ssb_sprom_rxgains target carries one slot per chain
	 * (see include/linux/ssb/ssb.h).
	 */
	out->trelnabyp[chain] = (packed >> 7) & 0x01;
	out->triso[chain]     = (packed >> 3) & 0x0f;
	out->elnagain[chain]  =  packed       & 0x07;
}

static void bcma_sprom_extract_r11(struct bcma_bus *bus, const u16 *sprom)
{
	static const u16 r11_pwr_info_offset[] = {
		SSB_SPROM11_PWR_INFO_CORE0,
		SSB_SPROM11_PWR_INFO_CORE1,
		SSB_SPROM11_PWR_INFO_CORE2,
	};
	u16 v;
	int i;

	/* --- Header (shared layout with rev 8) ------------------------ */
	for (i = 0; i < 3; i++) {
		v = sprom[SPOFF(SSB_SPROM11_IL0MAC) + i];
		*(((__be16 *)bus->sprom.il0mac) + i) = cpu_to_be16(v);
	}

	SPEX(board_rev, SSB_SPROM8_BOARDREV, ~0, 0);
	SPEX(board_type, SSB_SPROM1_SPID, ~0, 0);

	SPEX(country_code, SSB_SPROM11_CCODE, ~0, 0);
	SPEX(ant_available_a, SSB_SPROM11_ANTAVAIL, SSB_SPROM8_ANTAVAIL_A,
	     SSB_SPROM8_ANTAVAIL_A_SHIFT);
	SPEX(ant_available_bg, SSB_SPROM11_ANTAVAIL, SSB_SPROM8_ANTAVAIL_BG,
	     SSB_SPROM8_ANTAVAIL_BG_SHIFT);

	SPEX(txchain, SSB_SPROM11_TXRXC, SSB_SPROM8_TXRXC_TXCHAIN,
	     SSB_SPROM8_TXRXC_TXCHAIN_SHIFT);
	SPEX(rxchain, SSB_SPROM11_TXRXC, SSB_SPROM8_TXRXC_RXCHAIN,
	     SSB_SPROM8_TXRXC_RXCHAIN_SHIFT);
	SPEX(antswitch, SSB_SPROM11_TXRXC, SSB_SPROM8_TXRXC_SWITCH,
	     SSB_SPROM8_TXRXC_SWITCH_SHIFT);

	/* --- 5 GHz sub-band layout descriptor ------------------------- */
	SPEX(subband5gver, SSB_SPROM11_SUBBAND5GVER, 0x00ff, 0);

	/* --- Per-chain power info blocks ------------------------------ *
	 * Stride 0x28 bytes. Layout verified against the DSL-3580L dump.
	 * Only 3 chains (rev 11 maxes out at 3-stream), unlike rev 8's 4. */
	BUILD_BUG_ON(ARRAY_SIZE(r11_pwr_info_offset) >
		     ARRAY_SIZE(bus->sprom.core_pwr_info));

	for (i = 0; i < ARRAY_SIZE(r11_pwr_info_offset); i++) {
		struct ssb_sprom_core_pwr_info *p = &bus->sprom.core_pwr_info[i];
		u16 base = r11_pwr_info_offset[i];
		int j;

		p->maxp2ga = sprom[SPOFF(base + SSB_SPROM11_PWR_MAXP2GA)] & 0x00ff;

		for (j = 0; j < 3; j++)
			p->pa2ga[j] = sprom[SPOFF(base + SSB_SPROM11_PWR_PA2GA) + j];

		/* maxp5ga[4] is two consecutive u16 holding 4 × u8 packed
		 * little-endian: word_lo = (maxp5ga[1] << 8) | maxp5ga[0],
		 * word_hi = (maxp5ga[3] << 8) | maxp5ga[2]. */
		v = sprom[SPOFF(base + SSB_SPROM11_PWR_MAXP5GA)];
		p->maxp5ga[0] = v & 0x00ff;
		p->maxp5ga[1] = (v >> 8) & 0x00ff;
		v = sprom[SPOFF(base + SSB_SPROM11_PWR_MAXP5GA) + 1];
		p->maxp5ga[2] = v & 0x00ff;
		p->maxp5ga[3] = (v >> 8) & 0x00ff;

		for (j = 0; j < 12; j++)
			p->pa5ga[j] = sprom[SPOFF(base + SSB_SPROM11_PWR_PA5GA) + j];

		/* Rxgains decode. Two consecutive u16 hold the four sub-band
		 * triplets (eLNA gain, T/R isolation, T/R-eLNA bypass) for
		 * this chain, packed one byte per sub-band as
		 *
		 *   byte = (trelnabyp << 7) | (triso << 3) | elnagain
		 *
		 * Byte-to-sub-band assignment (verified by cross-reference of
		 * `wl srdump` against `wl nvram_dump` on the reference board):
		 *   word RXGAINS0 low byte  -> 5gm
		 *   word RXGAINS0 high byte -> 5gh
		 *   word RXGAINS1 low byte  -> 2g
		 *   word RXGAINS1 high byte -> 5gl  (UNII-1)
		 *
		 * Reference fit on the DSL-3580L dump (chain 0..2 identical):
		 *   words = 0xffff, 0xb300
		 *   5gm=(7,15,1)  -> (1<<7)|(15<<3)|7 = 0xff   ✓
		 *   5gh=(7,15,1)  -> 0xff                       ✓
		 *   2g =(0, 0,0)  -> 0x00                       ✓
		 *   5gl=(3, 6,1)  -> (1<<7)|(6<<3)|3  = 0xb3   ✓
		 *
		 * Three of the four bytes are saturated (0xff) or zero on the
		 * reference board, so 5gl=0xb3 is the only fully informative
		 * data point. The encoding fits all four bytes uniformly and
		 * the per-chain triplets in NVRAM match the same bytes on
		 * every chain. A second board with non-saturated 5gm/5gh and
		 * non-zero 2g rxgains would harden this further; the encoding
		 * is committed here as the working extraction with that
		 * caveat noted in sprom-rev11/README.md.
		 */
		v = sprom[SPOFF(base + SSB_SPROM11_PWR_RXGAINS0)];
		bcma_sprom_unpack_rxgains(&bus->sprom.rxgains_5gm, i,  v       & 0xff);
		bcma_sprom_unpack_rxgains(&bus->sprom.rxgains_5gh, i, (v >> 8) & 0xff);
		v = sprom[SPOFF(base + SSB_SPROM11_PWR_RXGAINS1)];
		bcma_sprom_unpack_rxgains(&bus->sprom.rxgains_2g,  i,  v       & 0xff);
		bcma_sprom_unpack_rxgains(&bus->sprom.rxgains_5gl, i, (v >> 8) & 0xff);
	}

	/* Per-chain pdoffset40ma triplet (verified — three identical u16
	 * at byte 0xCA reading 0x3222 on the reference board, matching
	 * NVRAM pdoffset40ma{0,1,2}=12834). */
	for (i = 0; i < 3; i++)
		bus->sprom.pdoffset40ma[i] =
			sprom[SPOFF(SSB_SPROM11_PDOFFSET40MA) + i];

	/* Power-per-rate region (byte 0x150..0x190) — rev-11 layout, NOT
	 * the rev-9 inheritance: mcsbw20/40 are followed by mcsbw80/160
	 * for each 5 GHz sub-band, and a pair of u16 (dot11agofdmhrbw202gpo,
	 * ofdmlrbw202gpo) sits between the 2.4 GHz BW40 entry and the
	 * 5 GHz BW20 entries.
	 *
	 * Sanity-check anchors on the reference board:
	 *   cckbw202gpo   = 0  (aa2g==0)
	 *   mcsbw205glpo  = 0xeca86420   (UNII-1 active)
	 *   mcsbw1605gXpo = 0  (160 MHz disabled by board profile)
	 */
	SPEX(cckbw202gpo,            SSB_SPROM11_CCKBW202GPO,            ~0, 0);
	SPEX(cckbw20ul2gpo,          SSB_SPROM11_CCKBW20UL2GPO,          ~0, 0);
	SPEX32(mcsbw202gpo,          SSB_SPROM11_MCSBW202GPO,            ~0, 0);
	SPEX32(mcsbw402gpo,          SSB_SPROM11_MCSBW402GPO,            ~0, 0);
	SPEX(dot11agofdmhrbw202gpo,  SSB_SPROM11_DOT11AGOFDMHRBW202GPO,  ~0, 0);
	SPEX(ofdmlrbw202gpo,         SSB_SPROM11_OFDMLRBW202GPO,         ~0, 0);
	SPEX32(mcsbw205glpo,         SSB_SPROM11_MCSBW205GLPO,           ~0, 0);
	SPEX32(mcsbw405glpo,         SSB_SPROM11_MCSBW405GLPO,           ~0, 0);
	SPEX32(mcsbw805glpo,         SSB_SPROM11_MCSBW805GLPO,           ~0, 0);
	SPEX32(mcsbw1605glpo,        SSB_SPROM11_MCSBW1605GLPO,          ~0, 0);
	SPEX32(mcsbw205gmpo,         SSB_SPROM11_MCSBW205GMPO,           ~0, 0);
	SPEX32(mcsbw405gmpo,         SSB_SPROM11_MCSBW405GMPO,           ~0, 0);
	SPEX32(mcsbw805gmpo,         SSB_SPROM11_MCSBW805GMPO,           ~0, 0);
	SPEX32(mcsbw1605gmpo,        SSB_SPROM11_MCSBW1605GMPO,          ~0, 0);
	SPEX32(mcsbw205ghpo,         SSB_SPROM11_MCSBW205GHPO,           ~0, 0);
	SPEX32(mcsbw405ghpo,         SSB_SPROM11_MCSBW405GHPO,           ~0, 0);
	SPEX32(mcsbw805ghpo,         SSB_SPROM11_MCSBW805GHPO,           ~0, 0);
	SPEX32(mcsbw1605ghpo,        SSB_SPROM11_MCSBW1605GHPO,          ~0, 0);

	/* TODO (still open — region byte 0x190..0x1B0 reads all zero on
	 * the reference board, so offset disambiguation by value-match is
	 * not possible from a single dump): mcslr5g{l,m,h}po,
	 * sb20in40{hr,lr}po, sb20in80and160{hr,lr}5g{l,m,h}po,
	 * sb40and80{hr,lr}5g{l,m,h}po, dot11agdup{hr,lr}po,
	 * pdoffset80ma[3]. The bcm47xx_sprom NVRAM fallback path covers
	 * these on SoC routers; a second rev-11 board with non-zero
	 * values in any of these fields would let the offsets be pinned
	 * here too.
	 *
	 * Also TODO from the front-end-module context block: femctrl,
	 * epagain{2g,5g}, pdgain{2g,5g}, tworangetssi{2g,5g},
	 * papdcap{2g,5g}, tssiposslope{2g,5g}, gainctrlsph,
	 * pdoffset2g40ma[3], pdoffset2g40mvalid. Same argument.
	 */
}

/* === END PARSER BODY ==================================================== */

/* Trampoline so test.c does not need the static linkage of the parser. */
void run_extract_r11(struct bcma_bus *bus, const u16 *sprom)
{
	bcma_sprom_extract_r11(bus, sprom);
}
